# -*- coding: utf-8 -*-
"""2024-09-02 Hello World

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qi5RD6rWdpeSPTYo0DlPJrc5PafGnpNR
"""

print("Hello World")